### ISSUE TITLE
'Search' Feature

### ISSUE THREAD

**Issue by Hitaro** [digitalcraftsman/hugo-material-docs#10]
Hi there

The upstream theme has a `search` feature that it's been removed here! As I see in [Docs](http://gohugo.io/overview/introduction/), 'search' is supported by Hugo! I was wondering why the search option of upstream theme has been removed from **hugo-material-docs**.

Anyway, I appreciate your work that make it possible for us to use another hugo theme for a documentation site.

UPDATE: I also saw https://github.com/digitalcraftsman/hugo-material-docs/issues/2 just now! Sorry for duplicating the issue.

**Comment by digitalcraftsman** [comment]
I disabled this feature until Hugo has native support for it. This issue motivated me to revisit my pull request for the implementation (see spf13/hugo#1853). Hopefully we can merge it soon. There's is already a draft for the next release but there no concrete plans for a release. But who knows :wink: 

Since this issue is a duplicate I'll close it.

**Comment by androidand** [comment]
Great theme, however I can't use it without the search function so I hope it will be added soon!
