### ISSUE TITLE
Error when generating content

### ISSUE THREAD

**Issue by dcu** [digitalcraftsman/hugo-material-docs#21]
I'm getting the following error when doing `hugo server`:

```
ERROR: 2016/05/20 10:06:50 template.go:119: reflect: call of reflect.Value.Type on zero Value in theme/partials/drawer.html
ERROR: 2016/05/20 10:06:50 general.go:203: Error while rendering section getting_started: template: theme/_default/list.html:30:17: executing "theme/_default/list.html" at <markdownify>: wrong type for value; expected string; got template.HTML
ERROR: 2016/05/20 10:06:50 template.go:119: reflect: call of reflect.Value.Type on zero Value in theme/partials/drawer.html
ERROR: 2016/05/20 10:06:50 template.go:119: reflect: call of reflect.Value.Type on zero Value in theme/partials/drawer.html
```
any idea what can it be?

**Comment by digitalcraftsman** [comment]
Hi @dcu,

would it be possible to send me your current setup for your documentation? It would make it easier to track down the issue. Sometimes the error messages of Hugo don't provide a good context :smile:

**Comment by aruscitti** [comment]
I am receiving a similar error.

ERROR: 2016/05/31 Error while rendering section : template: _default/list.html:30:17: executing "_default/list.html" at <markdownify>: wrong type for value; expected string; got template.HTML

Any fix?

**Comment by lifuzu** [comment]
Got a same error. My workaround is to remove the line #30 in layouts/_default/list.html
`{{ .Summary | markdownify }}`

**Comment by digitalcraftsman** [comment]
Hello together,

> @lifuzu: Got a same error. My workaround is to remove the line #30 in layouts/_default/list.html
{{ .Summary | markdownify }}

There is no need to delete the line. The problem is that the `markdownify` template function expects a string as input put `.Summary` is of type `template.HTML`. Therefore, I had to cast it before piping it.

573a2e9fc6daba258e4bbb197ef87aa8bccc3390 should fix this issue. Let me know if the issue is still present.

Regards,
Digitalcraftsman

PS: [This forum discussion](https://discuss.gohugo.io/t/error-message-when-rendering/3376) mentions the same issue.

**Comment by bflad** [comment]
Thanks for the quick fix! Works as expected.
