### ISSUE TITLE
example site fails to run - here is the fix  

### ISSUE THREAD

**Issue by gedw99** [digitalcraftsman/hugo-material-docs#81]
add this to the config at the top.

````
themesDir = "../.."

````

**Comment by andrewlow** [comment]
This is true ONLY if you are attempting to run the exampleSite 'in place'

Specifically

```
$ git clone git@github.com:digitalcraftsman/hugo-material-docs.git 
$ cd hugo-material-docs/exampleSite
$ hugo serve
```

If you are following along with the [README](https://github.com/digitalcraftsman/hugo-material-docs/blob/master/README.md) then you've either got your own config.toml file OR you've copied the one from the exampleSite up to the parent and the paths are different (and correct).

Suggest this issue is closed by the maintainers.

**Comment by gedw99** [comment]
your right . my mistake. sorry
